# Mark Forster Archive - GitHub Pages Configuration

title: Mark Forster Archive
description: A comprehensive archive of Mark Forster's productivity blog posts and community discussions
baseurl: ""
url: ""

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Navigation
header_pages:
  - index.md

# Social links (optional)
# github_username: username
# twitter_username: username

# Exclude from processing
exclude:
  - README.md
  - requirements.txt
  - "*.py"
  - "*.log"
  - "*.json"
  - venv/
  - __pycache__/
